# TODO: what api version to use
apiVersion: "pytorch/somethinghere"
kind: PyTorchJob
metadata:
  name: $app-$run
  labels:
    mlt-app-name: $app
spec:
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: $image
              name: pytorch
          restartPolicy: OnFailure
    - replicas: 1
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: $image
              name: pytorch
          restartPolicy: OnFailure
